### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by nkbt**
I ran through all npm scripts, checked all tests and built code, nothing fails with all new deps.

### CODE REVIEW

**Comment by SOSANA** [comment]
should add react-engine and reactjs to this as well

**Comment by nkbt** [comment]
Adding new stuff is off this one I believe. It's only about updating existing deps.

**Comment by SOSANA** [comment]
@nkbt should we be doing pr on the universal branch to update package.json file than? and also merging to that branch for all updates and tasks?

**Comment by nkbt** [comment]
If you need to add dependency for particular issue - update package.json in your issue accordingly. No need to separate the change obviously.

If you are about update other deps not related to your issue - separate PR then. 

Being captain obvious: in your PR include only updates related to the issue you are working on and strip out everything else that might be useful, but not related directly.

**Comment by nkbt** [comment]
Ah, btw, this PR does nothing with #23. I made before making comment on #23.

**Comment by SOSANA** [comment]
So your saying just update my package.json which makes sense but if I try to get it merged it won't pass do to not having the dependencies.

**Comment by nkbt** [comment]
Not sure I'm following you :). Just do not update package.json unless it is
required by the issue you are working on.

PS I'm off for now, sorry, will be back later.

**Pull request merged**
